### ISSUE TITLE
bug-2017-08-11

### ISSUE THREAD

**Issue by huangqist** [zdy1988/vue-metronic#1]
src\layouts\layout\layout.vue
不能删除以下代码：
`
          <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            <span></span>
          </a>
           `
删除会造成，ipad，mobile phone，没有菜单显示。

**Comment by zdy1988** [comment]
哈哈，多谢你的提醒
